
export const auth = {
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
  AUTH_LOGIN_PENDING: 'AUTH_LOGIN_PENDING',
  AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
  AUTH_LOGOUT_ERROR: 'AUTH_LOGOUT_ERROR',
  AUTH_LOGOUT_PENDING: 'AUTH_LOGOUT_PENDING',
  AUTH_AUTHORIZE_SUCCESS: 'AUTH_AUTHORIZE_SUCCESS',
  AUTH_AUTHORIZE_ERROR: 'AUTH_AUTHORIZE_ERROR',
  AUTH_AUTHORIZE_PENDING: 'AUTH_AUTHORIZE_PENDING',
}

export const users = {
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_ERROR: 'GET_USERS_ERROR',
  GET_USERS_PENDING: 'GET_USERS_PENDING',
}

export const exchangeRate = {
  GET_EXCHANGE_RATE_SUCCESS: 'GET_EXCHANGE_RATE_SUCCESS',
  GET_EXCHANGE_RATE_ERROR: 'GET_EXCHANGE_RATE_ERROR',
  GET_EXCHANGE_RATE_PENDING: 'GET_EXCHANGE_RATE_PENDING',
  GET_SYMBOLS_SUCCESS: 'GET_SYMBOLS_SUCCESS',
  GET_SYMBOLS_ERROR: 'GET_SYMBOLS_ERROR',
  GET_SYMBOLS_PENDING: 'GET_SYMBOLS_PENDING',
  GET_BASE_CHARACTERS_SUCCESS: 'GET_BASE_CHARACTERS_SUCCESS',
  GET_BASE_CHARACTERS_ERROR: 'GET_BASE_CHARACTERS_ERROR',
  GET_BASE_CHARACTERS_PENDING: 'GET_BASE_CHARACTERS_PENDING',
}
